#_target_: model.Triplet
#_target_: model.TripletNoMss
_target_: ${train.pl_target}

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: ${train.lr}
  weight_decay: 0.0

#scheduler: null
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: ${train.monitor_mode_sch}
  factor: 0.5
  patience: 10
  verbose: true

unet:
  _target_: ${train.target_unet}
  cfg: ${train}

featurenet:
  _target_: ${train.target_featurenet}
  cfg: ${train}
  inst_list: ${train.inst_list}
  f_size: ${train.f_size}
  mono: ${train.mono}
  to1d_mode: ${train.to1d_mode}
  order: ${train.order}
  mel: ${train.mel_featurenet}
  n_mels: ${train.n_mels}

# pretrain32
#ckpt_model_path: /home/imamura23/nas02home/outputs/pretrain/runs/2023-11-07/01-11-14/checkpoints/epoch_053.ckpt
# pretrain
#ckpt_model_path: /home/imamura23/nas02home/outputs/pretrain/runs/2023-11-07/00-58-42/checkpoints/epoch_016.ckpt
ckpt_model_path_unet: ${train.ckpt_model_path_unet}
ckpt_model_path_featurenet: ${train.ckpt_model_path_featurenet}

cfg: ${train}
