# @package _global_

defaults:
  - _self_
  - data: null # choose datamodule with `test_dataloader()` for evaluation
  - train: null
  - model: null
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: nnet/w
  #- experiment: nnet/x
  #- experiment: nnet/z
  #- experiment: nnet_mix/z
  #- override hydra/job_logging: colorlog
  #- override hydra/hydra_logging: colorlog

task_name: eval_nnet
#task_name: eval_nnet_mix

tags: ["dev"]

ckpt_pash: ???
