# @package _global_

defaults:
  - _self_
  - data: null # choose datamodule with `test_dataloader()` for evaluation
  - train: null
  - model: null
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: nnet/w

task_name: ???

tags: ["dev"]

ckpt_pash: ???
